### ISSUE TITLE
Slackline for team nature?

### ISSUE THREAD

**Issue by rorysedgwick** [dwyl/summer-2015#26]
I have a slackline (see https://www.youtube.com/watch?v=HodudVXgvl8) at home and i'm happy to bring it with me. 

Just wanted to check there would be a good place to set it up somewhere fairly near the house i.e. two medium size trees about 5-15 metres apart. It's pretty heavy so I want to make sure we could use it!

**Comment by iteles** [comment]
We were absolutely thinking of buying one of these! @nelsonic says he can think of a few places it could go.  🎉🎉

**Comment by nelsonic** [comment]
@rorysedgwick if you are up for transporting a slackline (_and giving us lessons_) it would be mindblowingly awesome! :+1:

**Comment by rorysedgwick** [comment]
I'm still pretty rubbish at it so not sure about the lessons but i'll definitely bring it then.

It sounds like it can be slightly hit or miss whether flight security allow the metal ratchet to be in your carry on luggage but I don't have a check in bag so i'll just have to gamble it.

**Comment by nelsonic** [comment]
Which airline are you flying @rorysedgwick ?

**Comment by rorysedgwick** [comment]
Ryanair. I've read accounts from people saying they've taken ratchets & climbing gear on planes (not Ryanair specifically) without a problem but a couple saying the security staff on the day just decided they wouldn't allow it and they had to check in that bag.  If there are any issues i'll just check it in the hold.

**Comment by nelsonic** [comment]
Ok. what are your thoughts on us ponying up for pre-booked hold luggage? are you staying in a hostel for a night before?

**Comment by rorysedgwick** [comment]
Oh well I really appreciate the offer but to add a hold/check-in bag to my flights now would cost £30 each way. Meaning that it would actually be cheaper to buy a slackline in Portugal :| i'm happy to take it in my cabin bag i'm sure it'll be fine.

Yeah i've booked a hostel in Porto for one night on the 9th.

**Comment by nelsonic** [comment]
@rorysedgwick how much _is_ a _good_ SlackLine? 
We'd be _happy_ to pay the £30 (_for hold luggage_) and give you a small luggage bag you can use. (_and not have to bring back to UK  - so only one-way hold luggage_)
We also need to transport a couple of extension leads so people can plug their laptop chargers in. see: #7 
And if the checked-in bag weight limit is <15kg we could also take the **box of Lego**...!! :open_mouth:

If you prefer to chance it with carrying the slackline in your hand luggage (_it will probably be fine_) go for  it! otherwise you'd be doing us a favour if you could help transport some of the _nice-to-haves_ we would _like_ to have there for the summer (like pairing keyboards, a couple of coding books and lego for "serious play") ...

there are options for buying one in Portugal http://www.monkeybiz-slackline.com/en/home ... however if you've already done the research to buy yours and you don't mind carrying it over, we'd offer to buy your "old" one off you and when you get back to UK you can get a new one...

Anyway, thanks _so much_ for reminding us about slacklining, we've been meaning to buy one for ages!!

**Comment by rorysedgwick** [comment]
@nelsonic The one I bought was the Maverick basic model which was £55 (bit more than I remember) and 15m long. As far as I can tell that's plenty long enough until you get seriously good, and the more advanced/expensive kits differ just in the length and in having double attachment systems to compensate for the increased force it will have to take.

If there are other bits & pieces that need to get to Portugal and have to be carried as check-in luggage then i'm happy to bundle it all up and take them. Having said that the options for buying a line in Portugal seem pretty good value and if you wanted one to keep then it would work out cheaper to buy either one of the 15m Elephant or Gibbon lines, both of which are meant to be pretty good for beginners.

I just set mine up for the first time this summer, i'd forgotten how much fun it is and how addictive!

**Comment by iteles** [comment]
So looking forward to trying this out!

**Comment by rorysedgwick** [comment]
So the simplest thing seems to be if I bring mine and leave it with you guys to keep.

If there is anything else that has to be transported as hold luggage, I will happily bring it and bundle the slackline in with it. If there isn't a huge amount to bring (which maybe it looks like) the slackline can fit in with my hand luggage and fingers crossed it makes it onto the plane.

**Comment by nelsonic** [comment]
Yeah, go for it on the hand luggage. :+1: 
Thanks a _million_! :wink: 
(_please put the bag I brought to FAC downstairs next to the fridge area so its out of the way, thanks_! )

**Comment by rorysedgwick** [comment]
Sure will do.

No problem, i'll just be praying I get it through and we get to use it! I've also grabbed that multisocket and will bring that along too.

**Comment by iteles** [comment]
@rorysedgwick Ace, thanks!

**Comment by nelsonic** [comment]
![legen-dary-545x353](https://cloud.githubusercontent.com/assets/194400/8488426/567d6ba4-210a-11e5-9351-0e7bdb45e51b.png)

**Comment by rorysedgwick** [comment]
I've made it to Porto with the slackline woohoo.

What time will you guys be going through Porto tomorrow and where would be an easy place to meet?
