### ISSUE TITLE
What are your thoughts on #dwylsummer 2015?

### ISSUE THREAD

**Issue by iteles** [dwyl/summer-2015#48]
Now we've come to the end of #dwylsummer2015 it would be really productive to get a 1-2 line impression from everyone on what they thought of it.

If people are willing to elaborate, I would also love to know:
- What worked well?
- What didn't work at all?
- What could we do better/start doing next summer?

**Comment by NataliaLKB** [comment]
##### What worked well?

What seemed to work the best on our trip was the first week. It was full of discovery and learning. Most days we ended feeling like we produced something of value. This is partly I think because we were given pretty clear things to look into and implement.

##### What didn't work at all?

The last week was much more unorganised and I think most people felt confused about what they were expected to produce. Since we were all working on a piece of the puzzle, it wasn't really clear where one piece ended and the next began. This resulting in rewriting the same code again and again.

##### What could we do better/start doing next summer?

For a project with so many people, I really think that you need an official team lead. I also think it would benefit from having more diagrams about the proposed architecture of the project to help people visualise how things will fit together.

It was the most fantastic trip though, and I really loved it. I do hope it happens again next year!!!!! 
:heart: :yellow_heart: :green_heart: :blue_heart: :purple_heart:

**Comment by iteles** [comment]
@NataliaLKB You're a :star:, thank you for your comments, we loved having you there! 

It'll definitely be happening again. Let's see if we can get some more contributions to make it better :blush:

**Comment by nelsonic** [comment]
thanks _again_ to @NataliaLKB for giving feedback 🎉 😍 
closing as I doubt the _rest_ of the people who attended _3 years_ ago will _remember_ anything ... 🙄

**Comment by iteles** [comment]
This year we'll "strongly suggest" people do this half way through and the day before they leave!

**Comment by nelsonic** [comment]
@iteles indeed ... 
and _next_ year we can `require` people to complete a form `before` they can go.
